apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhack-user-java
  labels:
    app: openhack-user-java
    sub: tripinsights
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: openhack-user-java
      sub: tripinsights
  template:
    metadata:
      labels:
        app: openhack-user-java
        sub: tripinsights
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: openhack-user-java
          image: registrypbi7366.azurecr.io/tripinsights/user-java:1.0
          env:
            - name: SQL_SERVER
              value: "${{ secrets.SQL_SERVER }}"
            - name: SQL_USER
              value: "${{ secrets.SQL_USER }}"
            - name: SQL_PASSWORD
              value: "${{ secrets.SQL_PASSWORD }}"
            - name: SQL_DBNAME
              value: "${{ secrets.SQL_DBNAME }}"
          livenessProbe:
            httpGet:
              path: /api/user-java/healthcheck
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /api/user-java/healthcheck
              port: 80
            initialDelaySeconds: 180
            periodSeconds: 10
            failureThreshold: 3
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: openhack-user-java
  labels:
    app: openhack-user-java
    sub: tripinsights
spec:
  ports:
    - name: dashboard
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: openhack-user-java
    sub: tripinsights
