name: build_poi
on:
  push:
    paths:
      - "src/poi/**"
    tags:
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            ref: main
      - name: ACR build
        id: acr
        uses: azure/docker-login@v1
        with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            cd ./src/poi
            docker build . -f ./../../dockerfiles/Dockerfile_3 --no-cache --build-arg IMAGE_VERSION="1.0" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`"-t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/poi:1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/poi:1.0
            cd ../../src/user-java
            docker build --no-cache --build-arg IMAGE_VERSION="1.0" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" . -f ./../../dockerfiles/Dockerfile_0 -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/user-java:1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/user-java:1.0
            cd ../../src/tripviewer
            docker build . -f ./../../dockerfiles/Dockerfile_1 --no-cache --build-arg IMAGE_VERSION="1.0" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/tripviewer:1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/tripviewer:1.0
            cd .../../src/userprofile
            docker build . -f ./../../dockerfiles/Dockerfile_2 --no-cache --build-arg IMAGE_VERSION="1.0" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`"-t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/userprofile:1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/userprofile:1.0
            cd ../../src/trip
            docker build . -f ./../../dockerfiles/Dockerfile_4 --no-cache --build-arg IMAGE_VERSION="1.0" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/trips:1.0
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/tripinsights/trips:1.0
